fintech_vault:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: localhost
      port: 8123
      user: default
      password: ""
      secure: false
    prod:
      type: clickhouse
      schema: default
      host: clickhouse
      port: 8123
      user: default
      password: ""
      secure: false
